services:
  auction-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:Z
    environment:
      - DATABASE_URL=sqlite:///./data/auction.db
      - SECRET_KEY=your-secret-key-change-in-production
    restart: unless-stopped
    user: "1001:1001"
    
  # Optional: Frontend development server (for development workflow)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - VITE_API_BASE=http://localhost:8000
    profiles:
      - dev

volumes:
  data:
    driver: local
